/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#04122e",
        "primary-container": "#1a2744",
        "on-primary": "#ffffff",
        "on-primary-container": "#828eb1",
        "secondary": "#0051d5",
        "secondary-container": "#316bf3",
        "secondary-fixed": "#dbe1ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#00174b",
        "surface": "#f9f9ff",
        "surface-dim": "#d3daea",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eefe",
        "surface-container-high": "#e2e8f8",
        "surface-container-highest": "#dce2f3",
        "on-surface": "#151c27",
        "on-surface-variant": "#45464d",
        "outline": "#75777e",
        "outline-variant": "#c5c6ce",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f9f9ff",
        "on-background": "#151c27",
        "inverse-surface": "#2a313d",
        "inverse-on-surface": "#ebf1ff",
        "inverse-primary": "#b9c6eb",
        "tertiary-fixed": "#ffdeab",
        "tertiary-fixed-dim": "#e3c28d",
        "on-tertiary-fixed": "#271900",
        "primary-fixed": "#d9e2ff",
        "primary-fixed-dim": "#b9c6eb",
        "success": "#2e7d32",
      },
      fontSize: {
        "display-queue": ["84px", { lineHeight: "100px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h2": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "h3": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
